webflow.settings:
  type: config_object
  mapping:
    api_key:
      type: string
      label: 'API Key'
    path_mappings:
      type: sequence
      sequence:
        type: mapping
        mapping:
          /Proj :
            type: string
            label: 'Drupal Path'
          webflow_page:
            type: string
            label: 'Webflow Page'
